### ISSUE TITLE
Percentile

### ISSUE THREAD

**Issue by rezayas** [rezayas/SimulationLib#6]
Can we add new a function to DiscreteTimeStatistic class that returns the specified percentile of the observations? 

**percentile(double alpha)** returns alpha*100th percentile of the observations, where alpha is a number between 0 and 1. 

Let's discuss if you have any questions. more info about percentile: https://en.wikipedia.org/wiki/Percentile

**Comment by nl384** [comment]
Added the feature, implementing with the nearest-rank method!
